version: '3.5'

services:
    db:
        build: ./myMongo
        command: ["--bind_ip_all"]
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./myMongo/users.js:/docker-entrypoint-initdb.d/users.js:ro
            - ./myMongo/data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: mydb
            MONGO_NON_ROOT_USERNAME: bat
            MONGO_NON_ROOT_PASSWORD: bat1234
        networks:
            - app-network
    api:
        build: ./myAPI
        ports:
            - 3000:3000
        volumes:
            - ./myAPI:/usr/src/app
            - /usr/src/app/node_modules
        command: nodemon index.js
        depends_on:
            - db
        environment:
            API_PORT: 3000
            MONGO_USERNAME: bat
            MONGO_PASSWORD: bat1234
            MONGO_HOSTNAME: db
            MONGO_PORT: 27017
            MONGO_DB: mydb
        networks:
            - app-network
    vue:
        build: ./myVue
        ports:
            - 8080:8080
        volumes:
            - ./myVue:/app
            - /app/node_modules
        command: npm run serve
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
